POST http://127.0.0.1:8000/api/v1/auth/sign-up/
Content-Type: application/json

{
    "username": "Ernist",
    "email": "ernistturgunbaev1@gmail.com",
    "password": "qwerty123456",
    "password_confirm": "qwerty123456",
    "user_status": "Пользователь",
    "last_name": "Turgunbaev"
}

###

POST http://127.0.0.1:8000/api/v1/auth/sign-up-confirmation/
Content-Type: application/json

{
    "email": "ernistturgunbaev1@gmail.com",
    "code": "185724"
}

###

POST http://127.0.0.1:8000/api/v1/auth/sign-in/
Content-Type: application/json

{
    "email": "ernistturgunbaev1@gmail.com",
    "password": "qwerty123456"
}

###
POST  http://127.0.0.1:8000/api/v1/auth/token/
Content-Type: application/json

{
    "email": "ernistturgunbaev1@gmail.com",
    "password": "qwerty123456"
}

###
POST  http://127.0.0.1:8000/api/v1/auth/token/refresh/
Content-Type: application/json

{
    "refresh": ".eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczODc2NzM5OSwiaWF0IjoxNzM4NjgwOTk5LCJqdGkiOiJjMjM3OGNiZmI5MGU0YjI3YWI1NjZhMTE3MjdmNWUyYSIsInVzZXJfaWQiOjd9.7T0_AQjlAes0B0Cj1LeCeF_UeKwyTziJYXKqOHhfYhQ"
}



###
POST  http://127.0.0.1:8000/api/v1/auth/request-password-reset/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4NzY2NDU1LCJpYXQiOjE3Mzg3NjYxNTUsImp0aSI6IjQ3MjUyZTJiZmY4MDRmY2FiN2VjODA1NDI4YzY0YjcyIiwidXNlcl9pZCI6MX0.AMkYUlGzelFG5UFeWpG2F0BhjK6ooAVv6sAxHV90Xdk


{
    "email": "ernistturgunbaev1@gmail.com"
}


### 
POST  http://127.0.0.1:8000/api/v1/auth/confirm-password-reset/
Content-Type: application/json

{
    "email": "ernistturgunbaev1@gmail.com",
    "new_password": "qwerty123456789",
    "new_password_confirm": "qwerty123456789"
}

###
POST http://localhost:8000/api/v1/auth/confirm-password-reset/?token=WDbWBK5iqlGEi6OnMqD5uG8-VdkKCuGSxCr3EBE5TvA 
Content-Type: application/json

{
    "email": "ernistturgunbaev1@gmail.com",
    "new_password": "qwerty123456789",
    "new_password_confirm": "qwerty123456789"
}