GET http://127.0.0.1:8000/api/v1/ordering/orders/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4NzgxMTk0LCJpYXQiOjE3Mzg3ODA4OTQsImp0aSI6ImM4NTIyMDc5NWZiNzQwYTQ4Y2IxYTUwMjEzZmIwYjQyIiwidXNlcl9pZCI6Mn0.xjs-jbwsBFE68XOiFpdbd33j8TRZED3HD0btnV_lAIU

###
POST http://127.0.0.1:8000/api/v1/ordering/orders/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4ODYxMzYxLCJpYXQiOjE3Mzg4NjEwNjEsImp0aSI6IjJjNjBhOWU0MGQ2NDQxMWY4M2Q2ZTVmZDVjNjUzMzZlIiwidXNlcl9pZCI6Mn0.eBZAIkfo316eqEY1dZSTwa6F9VNicZf9_3cmjr408r4

{
    "user": 3,
    "cart": 1,
    "address": 1,
    "status": "Оформлено",
    "quantity": 1,
    "total_sum": 1
}