GET http://127.0.0.1:8000/api/v1/products/products/1
Content-Type: application/json


###
GET  http://127.0.0.1:8000/api/v1/products/cart/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4Nzc2ODgwLCJpYXQiOjE3Mzg3NzY1ODAsImp0aSI6IjljMjQ1MjQ3N2YwMDRlMjZhNjgwZDc1NTJmNzI1NzBlIiwidXNlcl9pZCI6Mn0.-_z3J3tNzY9gFXzgXUobw2QnKGRVSr1QHi_ia_mlejs

{
    "user": 3,
    "product": 1
}