# Generated by Django 5.1.5 on 2025-01-27 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('None', 'Нет'), ('M', 'Мужской'), ('Ж', 'Женский')], max_length=255, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='userpymentcard',
            name='card',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Номер карты должен состоять из 12 цифр', regex='^\\d{12}$')], verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='userpymentcard',
            name='cvv',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='CVV должен состоять из 3 цифр', regex='^\\d{3}$')], verbose_name='CVV'),
        ),
    ]
