# Generated by Django 5.1.5 on 2025-01-28 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0002_alter_userprofile_gender_alter_userpymentcard_card_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'ordering': ['-created_at'], 'verbose_name': 'Адрес', 'verbose_name_plural': '2. Адреса'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Профиль', 'verbose_name_plural': '1. Профили'},
        ),
        migrations.AlterModelOptions(
            name='userpymentcard',
            options={'ordering': ['-created_at'], 'verbose_name': 'Карта пользователя', 'verbose_name_plural': '3. Карты ползователя'},
        ),
    ]
