# Generated by Django 5.1.5 on 2025-02-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0004_alter_userprofile_user_alter_userpymentcard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(db_index=True, default=2, max_length=255, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
