# Generated by Django 5.1.5 on 2025-02-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название блока')),
                ('text', models.TextField(verbose_name='Текст блока')),
                ('photo', models.ImageField(upload_to='block_photos', verbose_name='Изображение блока')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Блок компании',
                'verbose_name_plural': '1. Блок компании',
                'ordering': ['-created_at'],
            },
        ),
    ]
