# Generated by Django 5.1.5 on 2025-02-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_aboutus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='test',
            new_name='text',
        ),
    ]
