# Generated by Django 5.1.5 on 2025-02-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("block", "0003_rename_test_aboutus_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
