# Generated by Django 5.1.5 on 2025-02-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='frist_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.CharField(blank=True, choices=[('Админ', 'Админ'), ('Менеджер', 'Менеджер'), ('Пользователь', 'Пользователь')], default='Пользователь', max_length=50, null=True, verbose_name='Статус'),
        ),
    ]
