# Generated by Django 5.1.5 on 2025-02-03 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_frist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_status_approved',
        ),
    ]
