# Generated by Django 5.1.5 on 2025-01-26 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoriteproduct',
            old_name='product',
            new_name='product_id',
        ),
    ]
