# Generated by Django 5.1.5 on 2025-02-05 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal_data', '0002_remove_userprofile_email'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_service_name', models.CharField(max_length=100, verbose_name='Название сервиса оплаты')),
                ('photo', models.ImageField(upload_to='payment_services/images', verbose_name='Изображение')),
                ('qr_code', models.ImageField(upload_to='payment_qr_codes/images', verbose_name='QR-код')),
                ('prop_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер реквезита')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя Владельца карты')),
                ('whatsapp_url', models.TextField(blank=True, null=True, verbose_name='Ссылка на WhatsApp')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Сервис оплаты',
                'verbose_name_plural': '1. Сервисы оплаты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Оформлено', 'Оформлено'), ('Оплачено', 'Оплачено'), ('Отменено', 'Отменено'), ('Выполнено', 'Выполнено'), ('Не выполнено', 'Не выполнено')], default='Оформлено', max_length=20, verbose_name='Статус заказа')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('total_sum', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Сумма заказа')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='personal_data.useraddress', verbose_name='Адрес доставки')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.cart', verbose_name='Корзина товаров')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': '2. Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('Оплачено', 'Оплачено'), ('Отменено', 'Отменено'), ('Выполнено', 'Выполнено'), ('Не выполнено', 'Не выполнено')], default='Оплачено', max_length=20, verbose_name='Статус оплаты')),
                ('slug', models.SlugField(max_length=200, verbose_name='Слаг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='personal_data.useraddress', verbose_name='Адрес доставки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='ordering.order', verbose_name='Заказ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('payment_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='ordering.paymentservice', verbose_name='Сервис оплаты')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': '2. Оплаты',
                'ordering': ['-created_at'],
            },
        ),
    ]
