# Generated by Django 5.1.5 on 2025-01-28 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal_data', '0003_alter_useraddress_options_alter_userprofile_options_and_more'),
        ('products', '0002_alter_cart_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Оформлено', 'Оформлено'), ('Оплачено', 'Оплачено'), ('Отменено', 'Отменено'), ('Выполнено', 'Выполнено'), ('Не выполнено', 'Не выполнено')], default='Оформлено', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_sum', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='personal_data.useraddress')),
                ('cart', models.ManyToManyField(related_name='orders', to='products.cart')),
                ('pyment_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='personal_data.userpymentcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
