# Generated by Django 5.1.5 on 2025-02-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_alter_payment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Оформлено', 'Оформлено'), ('Оплачено', 'Оплачено'), ('Не оплачено', 'Не оплачено'), ('Отменено', 'Отменено')], default='Оформлено', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Оплачено', 'Оплачено'), ('Отменено', 'Отменено'), ('Ошибка оплаты', 'Ошибка оплаты')], default='Оплачено', max_length=20, verbose_name='Статус оплаты'),
        ),
    ]
